apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-game-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-game-backend
  template:
    metadata:
      labels:
        app: quiz-game-backend
    spec:
      containers:
      - name: quiz-game-backend
        image: rhearobinson23/quiz-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: SUPABASE_SECRET
          valueFrom:
            secretKeyRef:
              name: supabase-credentials
              key: supabase-secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: supabase-credentials
              key: supabase-secret
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"