apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-game-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-game-frontend
  template:
    metadata:
      labels:
        app: quiz-game-frontend
    spec:
      containers:
      - name: quiz-game-frontend
        image: rhearobinson23/quiz-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://quiz-game-backend:5000"