apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: quiz-game.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quiz-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: quiz-backend-service
            port:
              number: 5000