---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: >-
    cG9zdGdyZXNxbDovL3Bvc3RncmVzLnV1cmlkdGlwdG1uYmdkZWpvYm1uOlAlNDBuZGV5MDMxNkBhd3MtMC1hcC1zb3V0aC0xLnBvb2xlci5zdXBhYmFzZS5jb206NjU0My9wb3N0Z3Jlcw==
  JSONTOKEN: >-
    YWJjQDEyM181NA==